
name: demofortsb

services:
  db:
    image: postgres:16
    container_name: demofortsb-db
    environment:
      POSTGRES_DB: demofortsb
      POSTGRES_USER: tsb
      POSTGRES_PASSWORD: tsb
    ports:
      - "5432:5432"  # expose for local tools (optional)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tsb -d demofortsb"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: [demo]

  app:
    # expects a Dockerfile in project root
    build:
      context: .
      dockerfile: Dockerfile
    image: demofortsb:local
    container_name: demofortsb-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # --- Spring Datasource ---
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demofortsb
      SPRING_DATASOURCE_USERNAME: tsb
      SPRING_DATASOURCE_PASSWORD: tsb

      # --- JPA (adjust if using Flyway/Liquibase) ---
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # --- Security / JWT (example; replace in real deployments) ---
      APP_JWT_SECRET: "dev-demo-secret-change-me"
      APP_JWT_TTL_MINUTES: "60"

      # --- Actuator exposure so Prometheus can scrape ---
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
      MANAGEMENT_SERVER_PORT: "8080"

      # Optional: select a profile
      # SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [demo]

  prometheus:
    image: prom/prometheus:latest
    container_name: demofortsb-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=2d
    volumes:
      - ./ops/prometheus:/etc/prometheus:ro   # <— mount folder, not single file - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      app:
        condition: service_healthy
    networks: [demo]

  grafana:
    image: grafana/grafana:latest
    container_name: demofortsb-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      prometheus:
        condition: service_started
    networks: [demo]

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"  # Disable authentication
    ports:
      - "5341:80"         # Seq UI → http://localhost:5341
    volumes:
      - ./seq-data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks: [demo]

  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    environment:
      SEQ_ADDRESS: "http://seq:5341"
      # SEQ_API_KEY: "<optional key from Seq UI>"
    ports:
      - "12201:12201/udp" # GELF UDP (or expose TCP if you prefer)
    depends_on:
      seq:
        condition: service_healthy
    networks: [demo]

networks:
  demo:

volumes:
  db-data:
  prom-data:
  grafana-data:
  seq-data:
