
services:
  # Kong in DB-less mode
  kong:
    image: kong:3.9.1-ubuntu
    container_name: demofortsb-kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    ports:
      - "8000:8000" # Proxy port
      - "8001:8001" # Admin port (read-only in DB-less mode)
      - "8443:8443" # Kong proxy SSL
    volumes:
      - ./kong-config/kong.yml:/kong/declarative/kong.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demo
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Konga UI (uses existing postgres-local)
  konga:
    image: pantsel/konga:latest
    container_name: demofortsb-konga
    restart: always
    depends_on:
      - kong
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=postgres-local
      - DB_PORT=5432
      - DB_USER=konga
      - DB_PASSWORD=konga
      - DB_DATABASE=konga
      - NODE_ENV=production
    ports:
      - "1337:1337"
    networks:
      - demo
networks:
  demo:
    driver: bridge
    #external: true # use the already-existing 'demo' network
