global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "demofortsb-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8080"]
#      - targets: ["host.docker.internal:8080"]  # app running on Mac
    # Labels to identify this service
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: demofortsb-app

  # Kong API Gateway metrics - NEW!
  - job_name: "kong"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8001"]  # Kong Admin API
    # Labels to identify Kong
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: kong-gateway
    # Scrape more frequently for real-time API metrics
    scrape_interval: 5s