global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "demofortsb-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8080"]
#      - targets: ["host.docker.internal:8080"]  # app running on Mac
