name: Basic CI PipeLine

on:
  push:
    branches: [feature/cicd-implementation]
  pull_request:
    branches: [master]

env:
  JAVA_VERSION: '21'

jobs:

  # Shared build job - compiles once
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean compile -Dspring.profiles.active=local -B

      - name: Upload compiled classes
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: |
            target/classes/
            target/test-classes/
          retention-days: 1
  # No build job, to save time

  # Job1: Build and Unit Tests (no services needed)
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean compile -Dspring.profiles.active=local -B

      - name: Run unit tests
        run: mvn test -Dtest=**/*Test -Dspring.profiles.active=local -B

      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: target/surefire-reports/

  # Job2: Integration Tests (with Postgres and Redis)

  # Job3: Security Tests (runs in parallel)
