name: Basic CI PipeLine

on:
  push:
    branches: [feature/cicd-implementation]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '21'

jobs:

  # Shared build job - compiles once, if build, all other jobs need to use this, and do not need to compile
  # while few jobs, can use no build job, to save time, but need to compile in each job. comment out build job
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK ${{ env.JAVA_VERSION }}
#        uses: actions/setup-java@v4
#        with:
#          java-version: ${{ env.JAVA_VERSION }}
#          distribution: 'temurin'
#
#      - name: Cache Maven dependencies
#        uses: actions/cache@v4
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-maven-
#
#      - name: Build with Maven
#        run: mvn clean compile -Dspring.profiles.active=local -B
#
#      - name: Upload compiled classes
#        uses: actions/upload-artifact@v4
#        with:
#          name: compiled-classes
#          path: |
#            target/classes/
#            target/test-classes/
#          retention-days: 1


  # Job1: Build and Unit Tests via maven surefire plugin (no services needed)
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean compile -Dspring.profiles.active=local -B

      - name: Run unit tests
        run: mvn test -Dtest='**/*Test' -Dspring.profiles.active=local -B

      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: |
            **/target/surefire-reports/
          retention-days: 3

  # Job2: Integration Tests (with Postgres and Redis), even if no integration tests, can run, set in pom.xml
  integration-tests:
#    needs: build
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/demofortsb
      SPRING_DATASOURCE_USERNAME: tsb
      SPRING_DATASOURCE_PASSWORD: tsb
      SPRING_DATA_REDIS_HOST: localhost
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ""

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: demofortsb
          POSTGRES_USER: tsb
          POSTGRES_PASSWORD: tsb
        options: >-
          --health-cmd "pg_isready -U tsb -d demofortsb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7.0-alpine
        options: >-
          --health-cmd "redis-cli ping | grep PONG"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Download compiled classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: target/

      - name: Run integration tests via maven failsafe plugin
        run: mvn verify -Dspring.profiles.active=local -B


      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: |
            **/target/failsafe-reports/
          retention-days: 3

  # Job3: Security Tests (runs in parallel)
